name: "Semantic PR"

on: [pull_request]

jobs:
  main:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - name: Enable corepack
        run: corepack enable
        if: ${{ steps.release.outputs.releases_created }}
      
      - name: Install yarn
        run: yarn set version classic
        if: ${{ steps.release.outputs.releases_created }}

      - name: Install dependencies
        run: yarn install
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn lint:all
        if: ${{ steps.release.outputs.releases_created }}
      
      - run: yarn build
        if: ${{ steps.release.outputs.releases_created }}