name: "Lint and build"

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn' # cache node modules
          node-version: ${{ matrix.node }}
      - run: corepack enable
      - run: yarn set version classic
      - run: yarn
      - run: yarn run lint:all # lint code
